version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: tray_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - tray_network
  
  backend:
    build:
      context: ./backend
    container_name: tray_backend
    volumes:
      - ./backend:/var/www
    networks:
      - tray_network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: tray_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    networks:
      - tray_network

  db:
    image: mysql:8.0
    container_name: tray_mysql
    environment:
      MYSQL_ROOT_PASSWORD: tray_root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: tray_username
      MYSQL_PASSWORD: tray_password
      MYSQL_DATABASE: tray_database
    ports:
    - "13310:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tray_network

networks:
  tray_network:
    driver: bridge

volumes:
  db_data:
    driver: local
